name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Git tag or branch to build'
        required: false
        default: '1.3.0'

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || '1.3.0' }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Adjust Gradle distribution
        run: |
          sed -i 's|mirrors.cloud.tencent.com/gradle|services.gradle.org/distributions|' android/gradle/wrapper/gradle-wrapper.properties
          sed -i 's|gradle-8.13-all.zip|gradle-8.14-all.zip|' android/gradle/wrapper/gradle-wrapper.properties
          cat android/gradle/wrapper/gradle-wrapper.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Celechron-1.3.0-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
